---CREATE TABLE Colaborador (
--          ID_Colaborador INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
--		  Nome_Colaborador Varchar(Max) Not Null
--)


--ALTER TABLE Colaborador
     
--	 Add

--	 Situacao BIT NUll DEFAUlT 1,

--      DataInclusao DateTime Null Default GETDATE

--	  Go

--ALTER TABLE Colaborador

--       Add

--      Cpf_Colaborador Char(14) Not Null,
--	  Sobrenome_Colaborador Varchar (Max) Not Null,
--	  Endereco_Colaborador Varchar(max) Not Null,
--	  Telefone_Colaborador Char(14) Not Null,
--	  Email_Colaborador Varchar(Max) NOt NUll
--	  Go

--ALTER TAble Colaborador
--   Alter Column
--    Telefone_Colaborador VARCHAR(Max) Null

--	Go

--Alter Table Colaborador
--   ADD
--   Item_Produto Varchar (Max) Not Null

--   GO


--Alter Table  Colaborador

-- Drop Column

-- Item_Produto

-- GO

Drop Table Colaborador

Go
